source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.1"


pod 'CPAProxy', :git => 'https://github.com/OnionBrowser/CPAProxy.git', :commit => '2de56b6658bd453c825e23d5dbfa7ad3c2304e11'

#target "OnionBrowser" do
#
#end
#
#target "OnionBrowserTests" do
#
#end

