# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

app_identifier "com.miketigas.OnionBrowser"
team_id "331530"

skip_binary_upload true
skip_app_version_update true

# Only metadata upload
skip_screenshots true

# Only screenshot upload
#skip_metadata true
#overwrite_screenshots true
